version: '3.8'

services:
          
  database:
    restart: always                                                                       
    image: postgre-non-root
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    shm_size: ${DATABASE_SHM_SIZE}
    command: >
      postgres
      -c config_file=/etc/postgresql.conf
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_min_duration_statement=${DATABASE_LOG_MIN_DURATION_STATEMENT}
      -c shared_buffers=${DATABASE_SHARED_BUFFERS}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:                                                                    
      - "${DATABASE_DATA_DIR}:/var/lib/postgresql/data:z"
      - "${DATABASE_CONF_FILE}:/etc/postgresql.conf"
      - "${DATABASE_BACKUP_DIR}:/backup"
      - "${DATABASE_LOG_DIR}:/var/log/postgresql:z"
  redis:
    restart: always
    image: redis:latest
    sysctls:
      net.core.somaxconn: 1024