version: '3.8'

services:
  django_1:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      target: dev
    image: backend_dev
    command: bash -c "DJANGO_SETTINGS_MODULE=backend.settings python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --workers=${GUNICORN_WORKERS} --log-file=${GUNICORN_LOG}/gunicorn.log --log-level=${GUNICORN_LOG_LEVEL} -b '[::]:80' --worker-tmp-dir /dev/shm --timeout ${GUNICORN_TIMEOUT} --reload"
    volumes:
      - ./src:/backend/src
      - ${STATIC_ROOT}:${STATIC_ROOT}
      - ${MEDIA_ROOT}:${MEDIA_ROOT}
      - ${GUNICORN_LOG}:${GUNICORN_LOG}
      - ${DJANGO_LOG_DIR}:${DJANGO_LOG_DIR}
    ports:
      - "8084:80"
      - "8888:8888" # ipython notebook
    depends_on:
      - database
      - redis
    working_dir: /backend/src